### PR TITLE
Created NumberListener class

### PR DESCRIPTION
**Pull request by romadanskiy**
- Created a NumberListener class as requested in the issue #5 
- Added tests for NumberListener
- Also corrected NumpadListener tests to match NumberListener tests

### CODE REVIEW

**Comment by Empiree** [comment]
Hi @romadanskiy !

I will review your PR within a few days. Thank you! :)

**Review by Empiree — CHANGES_REQUESTED** [review]
You should also add numpad buttons, since we subscribe to all existing numeric buttons.

**Comment by romadanskiy** [comment]
@Empiree I came up with the idea to create a class (smth like KeyboardKeysHelper or KeyboardKeysProvider) that will provide collections of specific keyboard keys (numpad keys, number keys, etc.). What do you think?
There are other related questions here:
- Should this class be public or internal?
- Should we create another issue for this or I can do it here?

**Comment by Empiree** [comment]
> @Empiree I came up with the idea to create a class (smth like KeyboardKeysHelper or KeyboardKeysProvider) that will provide collections of specific keyboard keys (numpad keys, number keys, etc.). What do you think?

@romadanskiy 

Hi, the idea is interesting, we need to think what other collections we can put in there. The first thing that came to my mind is a collection of modifiers like Shift, Ctrl, Alt, etc. Also, you could create a collection of F1,F2,F3... buttons. 

The name of the class I suggest is `KeyboardKeySet`, it should be static and so it can be used by everyone, so it should be public. 

**It is better to start a new issue, describe all these ideas there and add to the list of ideas if necessary.** 

After this class is created, you will need to refactor classes such as `NumberListener` using `KeyboardKeySet`.

**Review by Empiree — APPROVED** [review]

**Pull request merged**
