### PR TITLE
Add keyboard layout enum and related updates

### PR DESCRIPTION
**Pull request by Gleebo**
#52 
First time contributing to an Open Source Project.
I have added an enum for keyboard layouts.

### CODE REVIEW

**Comment by Empiree** [comment]
Hey @Gleebo !

Thank you for your contributing :)

I will review it in a few days!

**Review by Empiree — APPROVED** [review]
Good!

**Comment by Gleebo** [comment]
> Good!

Wow, thanks!

I would like to keep contributing in my free time. Planning to study and play around with the codebase a bit more to add some meaningful unit tests & more. 

Unfortunately my windows PC broke the next day after I made this PR, only have a macbook to work on.

**Comment by Empiree** [comment]
Approved your changes. Thanks for your help in improving this library! :)

If you get any ideas to implement or want to do some more issues, that would be great!

Your changes will come in the next NuGet patch.

**Pull request merged**
