### PR TITLE
Edited the MouseListener introductory documentation.

### PR DESCRIPTION
**Pull request by jaketanis**
I reviewed the MouseListener introduction and provided some rewording and formatting suggestions.

If any of my edits take away from your original meaning, please let me know. 😄

Also, I renamed my branch, which is why the previous pull request closed.

### CODE REVIEW

**Comment by jaketanis** [comment]
@Empiree, I didn't realize i deleted the light bulb part of the note. I think that is a great thing to include for callouts, as it draws the reader's attention.

**Review by Empiree — APPROVED** [review]

**Comment by Empiree** [comment]
Merged @jaketanis . Thank you for your contribution! I'll fix the light bulb in the next commit. You can also do a review of the whole documentation, I think you can improve it perfectly! :)

**Comment by Empiree** [comment]
Ideally, the KeyboardListener and MouseListener documentation should be similar to each other, since they are engaged in the same task.

**Comment by jaketanis** [comment]
> Merged @jaketanis . Thank you for your contribution! I'll fix the light bulb in the next commit. You can also do a review of the whole documentation, I think you can improve it perfectly! :)

Sounds great! Thanks!

**Pull request merged**
